import pyTigerGraph as tg

host = ""
graphname = ""
username = ""
password = ""
secret_token = "29dhf29o9p9gd22r2f4fkdhqrd8jdof4"


conn = tg.TigerGraphConnection(host=host,restppPort="3306",gsPort="8080",
                               username=username, password=password,gcp=True,sslPort="8080", graphname=graphname)


conn.apiToken=conn.getToken(secret_token)
print("Connected")
print(conn.gsql('''
USE GRAPH CERN_EID_1
CREATE SCHEMA_CHANGE JOB schema_creation FOR GRAPH CERN_EID_1{

ADD VERTEX Party(PRIMARY_ID PartyGUID STRING,PartyType STRING,Status STRING,GDPRFlag BOOL,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME)WITH primary_id_as_attribute="TRUE",STATS="outdegree_by_edgetype";

ADD VERTEX Person(PRIMARY_ID PersonGUID STRING, LanguagePreference STRING,Status STRING, DOB STRING,GDPRFlag BOOL, CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME) WITH primary_id_as_attribute="TRUE",STATS="outdegree_by_edgetype";

ADD VERTEX Organization(PRIMARY_ID OrganizationGUID STRING, OutOfBusinessIndicator STRING, Website STRING,Status STRING, CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME) WITH primary_id_as_attribute="TRUE",STATS="outdegree_by_edgetype";

ADD VERTEX PersonName(PRIMARY_ID PersonNameGUID STRING,FirstName STRING, MiddleName STRING, LastName STRING, Prefix STRING,Suffix STRING, Title STRING ,FormattedName STRING, AlternateName STRING,VerifiedDQ BOOL,Status STRING, GDPRFlag BOOL, CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME) WITH primary_id_as_attribute="TRUE",STATS="outdegree_by_edgetype";

ADD VERTEX Email(PRIMARY_ID EmailGUID STRING, EmailAddress STRING,VerifiedSI BOOL, VerifiedDQ BOOL, Status STRING,GDPRFlag BOOL, CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING,LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME) WITH primary_id_as_attribute="TRUE",STATS="outdegree_by_edgetype";

ADD VERTEX Phone(PRIMARY_ID PhoneGUID STRING,PhoneType STRING, PhoneCountryCode STRING,Number STRING,Extension STRING,VerifiedSI BOOL, VerifiedDQ BOOL,Status STRING, CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME) WITH primary_id_as_attribute="TRUE",STATS="outdegree_by_edgetype";

ADD VERTEX Identity(PRIMARY_ID IdentityGUID STRING ,IdentifierType STRING, IdentifierValue STRING, IdentifierIssuer STRING,IdentifierLastChangeDate DATETIME,VerifiedFlag BOOL,Status STRING,GDPRFlag BOOL, CreatedDateTime DATETIME, UpdatedDateTime DATETIME,CreatedBy STRING,LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME) WITH primary_id_as_attribute="TRUE",STATS="outdegree_by_edgetype";

ADD VERTEX Address(PRIMARY_ID AddressGUID STRING, AddressLine1 STRING, AddressLine2 STRING,AddressLine3 STRING,AddressLine4 STRING, City STRING, CountyName STRING, ZipCode STRING,GeoCode STRING,FullAddress STRING,VerifiedAVS BOOL, VerifiedDQ BOOL,Status STRING,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME) WITH primary_id_as_attribute="TRUE",STATS="outdegree_by_edgetype";

ADD VERTEX Location(PRIMARY_ID LocationGUID STRING, LocationName STRING,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,LocationType STRING,Status STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME) WITH primary_id_as_attribute="TRUE",STATS="outdegree_by_edgetype";

ADD VERTEX StateCountry(PRIMARY_ID StateCountryCode STRING, StateCode STRING, StateName STRING,CountryName STRING,CountryISOCode STRING,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME) WITH primary_id_as_attribute="TRUE",STATS="outdegree_by_edgetype";

ADD VERTEX OrgName(PRIMARY_ID OrgNameGUID STRING, CustomerFullName STRING,  AlternateName STRING,VerifiedDQ BOOL,Status STRING,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME) WITH primary_id_as_attribute="TRUE",STATS="outdegree_by_edgetype";

ADD VERTEX PersonProfile(PRIMARY_ID PersonProfileGUID STRING,ProfileName STRING,AccountState STRING,DefaultCountry STRING,CPDBProfileID STRING,ProgressiveProfilingFlag BOOL,Status STRING,GDPRFlag BOOL, CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME) WITH primary_id_as_attribute="TRUE",STATS="outdegree_by_edgetype";

ADD VERTEX EmailDomain(PRIMARY_ID EmailDomainGUID STRING, DomainName STRING,VerifiedFlag BOOL,Status STRING, CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME) WITH primary_id_as_attribute="TRUE",STATS="outdegree_by_edgetype";

ADD VERTEX DellCustomerNumber(PRIMARY_ID GlobalDCN STRING,DCN STRING,BUID STRING,SourceName STRING,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING, Status STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME)WITH primary_id_as_attribute="TRUE",STATS="outdegree_by_edgetype";

ADD VERTEX UniversalCustomerID(PRIMARY_ID UCID STRING,SourceName STRING, CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING, Status STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME)WITH primary_id_as_attribute="TRUE",STATS="outdegree_by_edgetype";

ADD VERTEX DUNS(PRIMARY_ID DUNSNumber STRING,SourceName STRING,GDUNSIndc STRING,SiteStatusIndc STRING, SubsidiaryIndc STRING,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,Status STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME)WITH primary_id_as_attribute="TRUE",STATS="outdegree_by_edgetype";

ADD VERTEX PersonSourceKey(PRIMARY_ID PersonSourceKeyGUID STRING,SourceName STRING,SourceKeyValue STRING,SourceKeyName STRING,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME)WITH primary_id_as_attribute="TRUE",STATS="outdegree_by_edgetype";

ADD VERTEX AddressSourceKey(PRIMARY_ID AddressSourceKeyGUID STRING,SourceName STRING, SourceKeyValue STRING, BUID STRING, CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME)WITH primary_id_as_attribute="TRUE",STATS="outdegree_by_edgetype";

ADD VERTEX OrgProfile(PRIMARY_ID OrgProfileGUID STRING,CompanyProfileID STRING,PartyID STRING,CompanyProfileName STRING,Description STRING,RestrictedSite STRING,ProfileType STRING,VerifiedDQ BOOL,Status STRING, CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME)WITH primary_id_as_attribute="TRUE",STATS="outdegree_by_edgetype";

ADD VERTEX Hierarchy(PRIMARY_ID HierarchyGUID STRING,Name STRING,Status STRING, CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME)WITH primary_id_as_attribute="TRUE",STATS="outdegree_by_edgetype";

ADD VERTEX VirtualOrg(PRIMARY_ID VirtualOrgGUID STRING,Name STRING,ExperienceType STRING,ExperienceSubType STRING,Status STRING,CreatedByAppName STRING, LastUpdatedByAppName STRING, CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME)WITH primary_id_as_attribute="TRUE",STATS="outdegree_by_edgetype";

ADD VERTEX VirtualHierarchy(PRIMARY_ID VirtualHierarchyGUID STRING,Name STRING,ExperienceType STRING,ExperienceSubType STRING,Status STRING,CreatedByAppName STRING, LastUpdatedByAppName STRING, CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME)WITH primary_id_as_attribute="TRUE",STATS="outdegree_by_edgetype";

ADD VERTEX VirtualProfile(PRIMARY_ID VirtualProfileGUID STRING,Name STRING,ExperienceType STRING,ExperienceSubType STRING,Status STRING,CreatedByAppName STRING, LastUpdatedByAppName STRING, CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME)WITH primary_id_as_attribute="TRUE",STATS="outdegree_by_edgetype";

ADD VERTEX ChangeDataCapture(PRIMARY_ID VertexOrEdgeTypeName STRING, LastExtractDateTime DATETIME,LastExtractTransactionId STRING) WITH primary_id_as_attribute="TRUE",STATS="outdegree_by_edgetype";

ADD VERTEX VendorOfferGroup(PRIMARY_ID DataCaptureOfferGroup STRING,VendorFullName STRING,VendorCode STRING, OfferGroup STRING,ExperienceType STRING,ExperienceSubType STRING,ThirdPartyDataExpected BOOL,Status STRING,CreatedByNTID STRING, CreatedByEmail STRING, CreatedRecordSource STRING,CreatedDateTime DATETIME,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING,UpdatedRecordSource STRING, UpdatedDateTime DATETIME,CPDIngestionDateTime DATETIME,CPDUpdateDateTime DATETIME,CreatedBy STRING,TransactionID STRING,TransactionType STRING,LastUpdatedBy STRING) WITH primary_id_as_attribute="TRUE",STATS="outdegree_by_edgetype";

ADD VERTEX ThirdPartyCustomer(PRIMARY_ID ThirdPartyCustomerGUID STRING, ThirdPartyCustomerSourceId MAP<STRING,STRING>, ThirdPartyCustomerAttributes MAP<STRING,STRING>,UpdatedByAppName STRING, Status STRING, CreatedByAppName STRING,CreatedByNTID STRING, CreatedByEmail STRING, CreatedRecordSource STRING,CreatedDateTime DATETIME,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING,UpdatedRecordSource STRING, UpdatedDateTime DATETIME,CPDIngestionDateTime DATETIME,CPDUpdateDateTime DATETIME,CreatedBy STRING,TransactionID STRING,TransactionType STRING,LastUpdatedBy STRING) WITH primary_id_as_attribute="TRUE",STATS="outdegree_by_edgetype";

ADD VERTEX DFSAccount(PRIMARY_ID DFSAccountGUID STRING, DFSAccountNumber STRING,PaymentCode STRING,TokenID STRING,CreatedByNTID STRING, CreatedByEmail STRING, CreatedRecordSource STRING,CreatedDateTime DATETIME,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING,UpdatedRecordSource STRING, UpdatedDateTime DATETIME,CPDIngestionDateTime DATETIME,CPDUpdateDateTime DATETIME,CreatedBy STRING,TransactionID STRING,TransactionType STRING,LastUpdatedBy STRING,Status STRING )WITH primary_id_as_attribute="TRUE",STATS="outdegree_by_edgetype";

ADD VERTEX AppSourceKey(PRIMARY_ID AppSourceKeyGUID STRING,AppSourceID MAP<STRING,STRING>,AppSourceName STRING,Status STRING,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME,CreatedByAppName STRING, LastUpdatedByAppName STRING)WITH primary_id_as_attribute="TRUE",STATS="outdegree_by_edgetype";


ADD UNDIRECTED EDGE HAS_PERSON_NAME(FROM Person , TO PersonName,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME);

ADD UNDIRECTED EDGE HAS_SOURCE_KEY(FROM Person, TO PersonSourceKey,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME);

ADD UNDIRECTED EDGE PERSON_PROFILE_CONTACTS(FROM Person,TO PersonProfile,IsPrimary BOOL,BillingContactPreferenceFlag BOOL,ShippingContactPreferenceFlag BOOL,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME);

ADD UNDIRECTED EDGE PERSON_EMAIL(FROM Person,TO Email,PrimaryEmailFlag BOOL,Status STRING,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME);

ADD UNDIRECTED EDGE PROFILE_EMAIL(FROM Email,TO PersonProfile,Status STRING,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME);

ADD UNDIRECTED EDGE PERSON_PHONE(FROM Person,TO Phone,WorkFlag BOOL,HomeFlag BOOL,MobileFlag BOOL,FaxFlag BOOL,PrimaryPhoneFlag BOOL,Status STRING,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME);

ADD DIRECTED EDGE PERSON_LOCATION(FROM Person , TO Location,Status STRING,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME) ;

ADD DIRECTED EDGE HAS_LOCATION(FROM Address ,TO Location,Status STRING,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME);

ADD DIRECTED EDGE ORG_LOCATION(FROM Organization , TO Location,Status STRING,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME);

ADD UNDIRECTED EDGE ORG_PHONE(FROM Organization , TO Phone, PrimaryPhoneFlag BOOL,Status STRING,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME);

ADD UNDIRECTED EDGE ORG_PROFILE(FROM Organization , TO OrgProfile,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME);

ADD UNDIRECTED EDGE PERSON_BILLING_ADDRESS(FROM Person, TO Address,PrimaryAddressFlag BOOL,Status STRING,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME);

ADD UNDIRECTED EDGE PERSON_SHIPPING_ADDRESS(FROM Person, TO Address,PrimaryAddressFlag BOOL,Status STRING,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME);

ADD UNDIRECTED EDGE PERSON_MAILING_ADDRESS(FROM Person, TO Address,PrimaryAddressFlag BOOL,Status STRING,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME);

ADD UNDIRECTED EDGE ORG_BILLING_ADDRESS(FROM Organization, TO Address,PrimaryAddressFlag BOOL,Status STRING,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME);

ADD UNDIRECTED EDGE ORG_SHIPPING_ADDRESS(FROM Organization, TO Address,PrimaryAddressFlag BOOL,Status STRING,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME);

ADD UNDIRECTED EDGE ORG_MAILING_ADDRESS(FROM Organization, TO Address,PrimaryAddressFlag BOOL,Status STRING,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME);

ADD UNDIRECTED EDGE WORKS_FOR (FROM Person, TO Organization,Role STRING,Verified STRING,Status STRING,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME);

ADD UNDIRECTED EDGE PERSON_IDENTITY(FROM Person, TO Identity,Status STRING,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME);

ADD UNDIRECTED EDGE ORG_IDENTITY(FROM Organization, TO Identity,Status STRING,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME);

ADD UNDIRECTED EDGE ORG_NAME(FROM Organization, TO OrgName,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME);

ADD DIRECTED EDGE HAS_SUBSIDIARY( FROM Organization, TO Organization,Status STRING,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME) WITH REVERSE_EDGE="reverse_HAS_SUBSIDIARY";

ADD DIRECTED EDGE HAS_BRANCH(FROM Organization, TO Organization,Status STRING,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME) WITH REVERSE_EDGE="reverse_IS_BRANCH";

ADD DIRECTED EDGE HEADQUARTER(FROM Organization, TO Organization,Status STRING,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME) WITH REVERSE_EDGE="reverse_HEADQUARTER_OF";

ADD DIRECTED EDGE CHILD_OF(FROM Hierarchy, TO Hierarchy,Status STRING,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME) WITH REVERSE_EDGE="reverse_CHILD_OF";

ADD UNDIRECTED EDGE IN_STATE(FROM Address, TO StateCountry,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME);

ADD UNDIRECTED EDGE LINKED_TO(FROM EmailDomain, TO Email,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME);

ADD UNDIRECTED EDGE PERSON_PARTY(FROM Person, TO Party,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME);

ADD UNDIRECTED EDGE ORG_PARTY(FROM Organization,TO Party,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME);

ADD UNDIRECTED EDGE SAME_PERSON_AS(FROM Person,TO Person,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME);

ADD UNDIRECTED EDGE ORG_DCN(FROM Hierarchy,TO DellCustomerNumber,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME);

ADD UNDIRECTED EDGE ORG_UCID(FROM Hierarchy,TO UniversalCustomerID,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME);

ADD UNDIRECTED EDGE ORG_DUNS(FROM Hierarchy,TO DUNS,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME);

ADD UNDIRECTED EDGE PERSON_DCN(FROM Person, TO DellCustomerNumber,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME);

ADD UNDIRECTED EDGE PROFILE_DCN(FROM PersonProfile,TO DellCustomerNumber,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME);

ADD UNDIRECTED EDGE SAME_ORG_AS(FROM Organization,TO Organization,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME);

ADD UNDIRECTED EDGE ORG_DOMAIN(FROM OrgProfile,TO EmailDomain,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME);

ADD UNDIRECTED EDGE PERSON_TO_ORG_PROFILE(FROM PersonProfile,TO OrgProfile,Role STRING,Status STRING,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME);

ADD UNDIRECTED EDGE HAS_HIERARCHY(FROM Organization,TO Hierarchy,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME);

ADD UNDIRECTED EDGE SPANS(FROM Hierarchy,TO VirtualHierarchy,Status STRING,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME,CreatedByAppName STRING,LastUpdatedByAppName STRING);

ADD UNDIRECTED EDGE VIRTUAL_UCID(FROM VirtualHierarchy, TO UniversalCustomerID, Status STRING,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME,CreatedByAppName STRING,LastUpdatedByAppName STRING);

ADD UNDIRECTED EDGE VIRTUAL_DCN(FROM VirtualHierarchy, TO DellCustomerNumber, Status STRING, CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME,CreatedByAppName STRING,LastUpdatedByAppName STRING);

ADD UNDIRECTED EDGE ADDRESS_KEYS(FROM Address,TO AddressSourceKey,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME);

ADD UNDIRECTED EDGE HAS_ACCESS(FROM PersonProfile,TO VirtualProfile,Role STRING,Status STRING,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME,CreatedByAppName STRING,LastUpdatedByAppName STRING);

ADD UNDIRECTED EDGE PARTNER_OF(FROM Organization,TO Organization,PartyRole STRING,Status STRING,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME);

ADD UNDIRECTED EDGE HAS_VIRTUAL_ORG(FROM VirtualHierarchy,TO VirtualOrg,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME,CreatedByAppName STRING,LastUpdatedByAppName STRING);

ADD UNDIRECTED EDGE HAS_VIRTUAL_PROFILE(FROM VirtualOrg,TO VirtualProfile,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME,CreatedByAppName STRING,LastUpdatedByAppName STRING);

ADD UNDIRECTED EDGE HAS_ADDRESS_ID(FROM AddressSourceKey,TO DellCustomerNumber,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME);

ADD UNDIRECTED EDGE HAS_SITE_DUNS(FROM AddressSourceKey,TO DUNS,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME);

ADD UNDIRECTED EDGE DFS_ACCOUNT(FROM PersonProfile, TO DFSAccount,Status STRING,CreatedByNTID STRING, CreatedByEmail STRING, CreatedRecordSource STRING,CreatedDateTime DATETIME,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING,UpdatedRecordSource STRING, UpdatedDateTime DATETIME,CPDIngestionDateTime DATETIME,CPDUpdateDateTime DATETIME,CreatedBy STRING,TransactionID STRING,TransactionType STRING,LastUpdatedBy STRING);
    
ADD UNDIRECTED EDGE ORG_REFERENCE_NAME (FROM Organization , TO OrgName,Source STRING, Status STRING,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME);
    
ADD UNDIRECTED EDGE ORG_REFERENCE_ADDRESS (FROM Organization , TO Address,Source STRING, Status STRING,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME);

ADD UNDIRECTED EDGE ORG_REFERENCE_PHONE (FROM Organization , TO Phone,Source STRING, Status STRING,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME);
    
ADD UNDIRECTED EDGE REFERENCE_DUNS (FROM Organization, TO DUNS,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME);
    
ADD UNDIRECTED EDGE UCID_NAME (FROM UniversalCustomerID, TO OrgName,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME);
    
ADD UNDIRECTED EDGE DCN_NAME (FROM DellCustomerNumber, TO OrgName,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME);

ADD UNDIRECTED EDGE ORG_UCID_ADDRESS (FROM Organization, TO Address,Status STRING, CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME);

ADD UNDIRECTED EDGE UCID_ADDRESS (FROM UniversalCustomerID, TO Address,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME);

ADD UNDIRECTED EDGE THIRD_PARTY_CUSTOMER(FROM VirtualHierarchy, TO ThirdPartyCustomer, Status STRING, CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME,CreatedByAppName STRING,LastUpdatedByAppName STRING);

ADD UNDIRECTED EDGE HAS_THIRDPARTYCUSTOMER(FROM VendorOfferGroup, TO ThirdPartyCustomer,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME);

ADD UNDIRECTED EDGE PROFILE_PHONE(FROM Phone, TO PersonProfile,Status STRING,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME);

ADD DIRECTED EDGE VIRTUAL_CHILD_OF(FROM VirtualHierarchy,TO VirtualHierarchy,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME,CreatedByAppName STRING,LastUpdatedByAppName STRING) WITH REVERSE_EDGE="reverse_VIRTUAL_CHILD_OF";

ADD UNDIRECTED EDGE HAS_APPSOURCEKEY(FROM VirtualHierarchy , TO AppSourceKey,CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME,CreatedByAppName STRING, LastUpdatedByAppName STRING);

ADD DIRECTED EDGE RELATED_TO(FROM VirtualHierarchy,TO VirtualHierarchy,RelationshipType STRING, CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME,CreatedByAppName STRING, LastUpdatedByAppName STRING) WITH REVERSE_EDGE="reverse_RELATED_TO";

ADD UNDIRECTED EDGE VIRTUAL_ADDRESS_ID(FROM VirtualHierarchy , TO AddressSourceKey, CreatedDateTime DATETIME, UpdatedDateTime DATETIME, CreatedBy STRING, LastUpdatedBy STRING, CreatedRecordSource STRING,UpdatedRecordSource STRING,TransactionID STRING,TransactionType STRING,CreatedByNTID STRING,CreatedByEmail STRING,LastUpdatedByNTID STRING,LastUpdatedByEmail STRING, CPDUpdateDateTime DATETIME, CPDIngestionDateTime DATETIME,CreatedByAppName STRING, LastUpdatedByAppName STRING);



}
RUN SCHEMA_CHANGE JOB schema_creation
DROP JOB schema_creation
'''))
